### ISSUE TITLE
Overlay Controls

### ISSUE THREAD

**Issue by Afy65** [hudec117/Mpv.WPF#3] opened 2018-05-24 14:42 UTC
Its not possible to overlay controls over the instance of the player?
Please correct me if I'm incorrect?
Loving your work though :)

Thanks

**Comment by hudec117** [comment] 2018-05-25 11:32
Hiya Afy65,

Yeah that is a known limitation at the moment. I will add a note to the README explaining this.

I'm unsure what the cause of this is, it's definitely something to do with how mpv renders the video onto the screen.

The mpv C API has another more complicated but also more configurable way of rendering video which my prove useful here. It's something I plan to look into.

Thanks : )

**Comment by Afy65** [comment] 2018-05-25 14:09
Okay :) thanks for you reply

**Comment by mysteryx93** [comment] 2018-06-10 04:47
That's a common issue with embedded WinForms sections within WPF applications. Look at AirspacePopup, this should work. https://stackoverflow.com/questions/6087835/can-i-overlay-a-wpf-window-on-top-of-another/6452940#6452940

**Comment by hudec117** [comment] 2018-06-10 16:19
Thanks @mysteryx93!

I do not have time to implement this at the moment but feel free to try it yourself (or anyone else) if you're interested.

**Comment by mysteryx93** [comment] 2018-06-10 21:27
Yes this isn't part of the project, which really contains no UI at all -- but is something for us to implement. I'm starting to work on a player UI that could potentially be used with any media player, if this works out as planned.

**Comment by hudec117** [comment] 2018-06-15 13:18
Closed as project is deprecated. Open an issue on Mpv.NET if you need more help.

**Closed by hudec117** 2018-06-15 13:18 UTC
